"""report source_files list

Revision ID: 29323fd5f2a8
Revises: ca1ab0c468f7
Create Date: 2026-08-05 12:34:42.478373
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29323fd5f2a8'
down_revision: Union[str, None] = 'ca1ab0c468f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_metadata', sa.Column('source_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_metadata', 'source_files')
    # ### end Alembic commands ###
