"""job destination_addrs filter

Revision ID: ca1ab0c468f7
Revises: 2190cab60451
Create Date: 2026-08-05 12:02:10.705545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1ab0c468f7'
down_revision: Union[str, None] = '2190cab60451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_jobs', sa.Column('destination_addrs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_jobs', 'destination_addrs')
    # ### end Alembic commands ###
