"""extraction jobs and report metadata

Revision ID: dba41b201ed4
Revises: f09a10b0d321
Create Date: 2026-08-04 17:56:24.800322
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba41b201ed4'
down_revision: Union[str, None] = 'f09a10b0d321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_shortcodes', sa.JSON(), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_job_id'), 'extraction_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_extraction_jobs_status'), 'extraction_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_user_id'), 'extraction_jobs', ['user_id'], unique=False)
    op.create_table('report_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('csv_filename', sa.String(length=255), nullable=False),
    sa.Column('zip_filename', sa.String(length=255), nullable=False),
    sa.Column('metadata_filename', sa.String(length=255), nullable=False),
    sa.Column('csv_path', sa.String(length=1024), nullable=False),
    sa.Column('zip_path', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json_path', sa.String(length=1024), nullable=False),
    sa.Column('csv_row_count', sa.Integer(), nullable=False),
    sa.Column('source_file_count', sa.Integer(), nullable=False),
    sa.Column('missing_file_count', sa.Integer(), nullable=False),
    sa.Column('rows_scanned', sa.Integer(), nullable=False),
    sa.Column('bad_timestamp_rows', sa.Integer(), nullable=False),
    sa.Column('zip_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_metadata_job_id'), 'report_metadata', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_metadata_job_id'), table_name='report_metadata')
    op.drop_table('report_metadata')
    op.drop_index(op.f('ix_extraction_jobs_user_id'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_status'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_job_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    # ### end Alembic commands ###
