"""email deliveries

Revision ID: f78e6a7ffaad
Revises: 7a5febf336a5
Create Date: 2026-08-05 15:23:08.605729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e6a7ffaad'
down_revision: Union[str, None] = '7a5febf336a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_deliveries_job_id'), 'email_deliveries', ['job_id'], unique=False)
    op.create_index(op.f('ix_email_deliveries_status'), 'email_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_deliveries_status'), table_name='email_deliveries')
    op.drop_index(op.f('ix_email_deliveries_job_id'), table_name='email_deliveries')
    op.drop_table('email_deliveries')
    # ### end Alembic commands ###
